login:
  oidc_enabled:
    default: false
    client: true
  oidc_client_id: ''
  oidc_client_secret: ''
  #oidc_authorize_url: ''
  #oidc_token_url: ''
  oidc_issuer_url: ''
  oidc_user_json_url: ''
  oidc_json_user_id_path: ''
  oidc_json_username_path: ''
  oidc_json_name_path: ''
  oidc_json_email_path: ''
  oidc_json_groups_path: ''
  oidc_email_verified: false
  oidc_send_auth_header: true
  oidc_debug_auth: false
  oidc_authorize_options:
    default: 'scope'
    type: list
  oidc_button_title:
    default: 'with OpenID Connect'
    client: true
